java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.7.0" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.7/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.7.2" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.7.2/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.7.3" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.7.3/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.8.0" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.8/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.8.1" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.8.1/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-0.8.3" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-0.8.3/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-1.0.0" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-1.0/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/apache/cassandra.git" "cassandra" "cassandra-1.1.0" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-cassandra/apache-cassandra-1.1/Validated"
