java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.12.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.12_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.13.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.13_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.14.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.14_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.15.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.15_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.16.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.16_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.17.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.17_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.18.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.18_OK\Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "InappropriateIntimacy" "https://github.com/elastic/elasticsearch.git" "elasticsearch" "v0.19.0" "D:\PhD\Progetti\CodeSmells\jDecaf\dataset\elastic-search-data\elasticsearch-elasticsearch-0.19_OK\Validated"
