java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.11" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.11_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.13" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.13_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.14" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.14_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.15" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.15_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.16" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.16_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.17" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.17_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.18" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.18_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "wicket-1.4.19" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.19_OK/Validated"

java -Djava.util.Arrays.useLegacyMergeSort=true -jar "D:/Documenti/NetbeansProjects/jDECAF_ML/target/jDECAF_ML-1.0-SNAPSHOT-jar-with-dependencies.jar" "D:/PhD/Progetti/CodeSmells/jDecaf/data" "LongParameterList" "https://github.com/apache/wicket.git" "wicket" "release/wicket-1.4.20" "D:/PhD/Progetti/CodeSmells/jDecaf/dataset/apache-wicket-data/l0rdn1kk0n-wicket-1.4.20_OK/Validated"
